### ISSUE TITLE
pdf file has different outputs when compiling on Linux vs Windows

### ISSUE THREAD

**Issue by marquesarthur** [briandealwis/ubcdiss#10]
Hi Brian,

Thanks for providing such a useful repo. I recently had someone talking about how he could not compile the diss.tex file properly in his Windows 10 environment albeit I did not notice anything wrong in my Ubuntu environment.  Upon further inspection, it seems that there are some font differences on Windows and the acronym package. There are some other differences but I can't reproduce them right now. 

Has anyone noticed this before? If so, are you aware of potential differences between operating systems?

Cheers

**Comment by briandealwis** [comment]
Sorry for this long delay — this notification was caught by my spam filter.

My wife used this template with MikTeX on Windows. But that was a decade ago.

The fonts used for the acronym package are configurable:

https://github.com/briandealwis/ubcdiss/blob/30f8e7056f0363cc7c224cc870ba03d1584326f4/diss.tex#L132

**Comment by marquesarthur** [comment]
No worries. Changing the fonts fixed the differences.
